# Generated by Django 4.2.10 on 2024-02-08 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uzman', '0002_degerlendirme_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degerlendirme',
            name='user',
        ),
        migrations.AlterField(
            model_name='degerlendirme',
            name='musteri_temsilcisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirmeler', to=settings.AUTH_USER_MODEL, verbose_name='Müşteri Temsilcisi'),
        ),
    ]
