# Generated by Django 5.0.1 on 2024-02-05 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acilis_karsilama', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('etkin_dinleme_anlama', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('analiz_etkin_soru', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('gorusme_kirliligi', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('ses_tonu', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('sorun_sahiplenme', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('empati', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('sure_stres_yonetimi', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('dogru_yonlendirme', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('bilgi_paylasimi', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('uygun_kapanis', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('ilgili_yonlendirilen_ekip_bilgi', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('hatali_sonlandirma', models.BooleanField(default=False)),
                ('kayit_alma_hatasi', models.BooleanField(default=False)),
                ('kaba_davranis', models.BooleanField(default=False)),
                ('irtibat_numarasi_alma_hatasi', models.BooleanField(default=False)),
                ('mt_hatti_acik_birakma', models.BooleanField(default=False)),
                ('kvkk_uyumu', models.BooleanField(default=False)),
                ('ilgisiz_davranis', models.BooleanField(default=False)),
                ('soz_kesme', models.BooleanField(default=False)),
                ('uygunsuz_karsilama', models.BooleanField(default=False)),
                ('farkli_icerikle_ilgilenme', models.BooleanField(default=False)),
                ('yansayan_sesler', models.BooleanField(default=False)),
                ('kisisel_bilgileri_paylasma', models.BooleanField(default=False)),
                ('prosedur_mevzuata_aykiri_bilgi', models.BooleanField(default=False)),
                ('temsilci', models.CharField(max_length=100)),
                ('cagri_kuyrugu', models.CharField(max_length=100)),
                ('telefon_numarasi', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Telefon numarası başında sıfır olmadan 10 haneli olmalıdır.', regex='^\\d{10}$')])),
                ('cagri_tarihi', models.DateField()),
                ('aciklamalar', models.TextField()),
                ('ek_dosya', models.FileField(blank=True, null=True, upload_to='degerlendirmeler/')),
            ],
        ),
    ]
